# Generated by Django 5.2.8 on 2025-11-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_restaurant_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ward',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '千種区'), (2, '東区'), (3, '北区'), (4, '西区'), (5, '中村区'), (6, '中区'), (7, '昭和区'), (8, '瑞穂区'), (9, '熱田区'), (10, '中川区'), (11, '港区'), (12, '南区'), (13, '守山区'), (14, '名東区'), (15, '天白区'), (16, '緑区')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')]),
        ),
    ]
