# Generated by Django 5.2.8 on 2025-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_restaurant_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='genre',
            field=models.CharField(choices=[('ogura_toast', '小倉トースト'), ('dote_ni', 'どて煮'), ('tebasaki', '手羽先'), ('tenmusu', '天むす'), ('taiwan_ramen', '台湾ラーメン'), ('ankake_spaghetti', 'あんかけスパゲッティ'), ('kishimen', 'きしめん'), ('miso_nikomi_udon', '味噌煮込みうどん'), ('miso_katsu', '味噌カツ'), ('hitsumabushi', 'ひつまぶし')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='weekday',
            field=models.IntegerField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ward',
            field=models.CharField(choices=[('chikusa', '千種区'), ('higashi', '東区'), ('kita', '北区'), ('nishi', '西区'), ('nakamura', '中村区'), ('naka', '中区'), ('showa', '昭和区'), ('mizuho', '瑞穂区'), ('atsuta', '熱田区'), ('nakagawa', '中川区'), ('minato', '港区'), ('minami', '南区'), ('moriyama', '守山区'), ('meito', '名東区'), ('tempaku', '天白区'), ('midori', '緑区')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
