# Generated by Django 5.2.8 on 2025-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_restaurant_category_restaurant_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='genre',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='genre',
            field=models.ManyToManyField(to='base.genre'),
        ),
    ]
