# Generated by Django 5.2.8 on 2025-11-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_genre_remove_restaurant_genre_restaurant_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ward', models.CharField(choices=[('chikusa', '千種区'), ('higashi', '東区'), ('kita', '北区'), ('nishi', '西区'), ('nakamura', '中村区'), ('naka', '中区'), ('showa', '昭和区'), ('mizuho', '瑞穂区'), ('atsuta', '熱田区'), ('nakagawa', '中川区'), ('minato', '港区'), ('minami', '南区'), ('moriyama', '守山区'), ('meito', '名東区'), ('tempaku', '天白区'), ('midori', '緑区')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpotSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_sub_area', to='base.spot')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sub_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='base.spotsubarea'),
            preserve_default=False,
        ),
    ]
