# Generated by Django 5.2.8 on 2025-11-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_spot_spotsubarea_restaurant_sub_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotsubarea',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
