# Generated by Django 5.2.8 on 2025-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_spotsubarea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotsubarea',
            name='ward',
            field=models.CharField(choices=[('chikusa', '千種区'), ('higashi', '東区'), ('kita', '北区'), ('nishi', '西区'), ('nakamura', '中村区'), ('naka', '中区'), ('showa', '昭和区'), ('mizuho', '瑞穂区'), ('atsuta', '熱田区'), ('nakagawa', '中川区'), ('minato', '港区'), ('minami', '南区'), ('moriyama', '守山区'), ('meito', '名東区'), ('tempaku', '天白区'), ('midori', '緑区')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
