# Generated by Django 5.2.8 on 2025-11-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_spotsubarea_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotsubarea',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='base.spot'),
        ),
        migrations.AddConstraint(
            model_name='spotsubarea',
            constraint=models.UniqueConstraint(fields=('spot', 'name', 'ward'), name='unique_spot_subarea'),
        ),
    ]
