# Generated by Django 5.2.8 on 2025-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_userbilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_datetime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
