# Generated by Django 5.2.8 on 2025-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_reservation_reserved_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_party_size',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_party_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='weekday',
            field=models.TextField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')]),
        ),
        migrations.AddConstraint(
            model_name='openinghour',
            constraint=models.UniqueConstraint(fields=('restaurant', 'weekday', 'open_time', 'close_time'), name='unique_openinghour_slot'),
        ),
    ]
