# Generated by Django 5.2.8 on 2025-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_reservation_date_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ward',
            field=models.CharField(choices=[('minato', '港区'), ('chikusa', '千種区'), ('atsuta', '熱田区'), ('naka', '中区'), ('kita', '北区'), ('higashi', '東区'), ('nishi', '西区'), ('nakamura', '中村区')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ward',
            field=models.CharField(choices=[('minato', '港区'), ('chikusa', '千種区'), ('atsuta', '熱田区'), ('naka', '中区'), ('kita', '北区'), ('higashi', '東区'), ('nishi', '西区'), ('nakamura', '中村区')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spotsubarea',
            name='ward',
            field=models.CharField(choices=[('minato', '港区'), ('chikusa', '千種区'), ('atsuta', '熱田区'), ('naka', '中区'), ('kita', '北区'), ('higashi', '東区'), ('nishi', '西区'), ('nakamura', '中村区')], max_length=20),
        ),
    ]
